export const NINE_BOX_DEFINITIONS = [
  {
    boxIndex: 1,
    label: 'Underperformer',
    description: 'Low performance and low potential. Action plan or exit needed.',
    targetPercentage: 5,
    perf: 'LOW' as const,
    pot: 'LOW' as const,
  },
  {
    boxIndex: 2,
    label: 'Effective Performer',
    description: 'Steady current output with specialized or bounded scope.',
    targetPercentage: 10,
    perf: 'MEDIUM' as const,
    pot: 'LOW' as const,
  },
  {
    boxIndex: 3,
    label: 'Trusted Professional',
    description: 'Exceptional domain execution with focus in current band.',
    targetPercentage: 15,
    perf: 'HIGH' as const,
    pot: 'LOW' as const,
  },
  {
    boxIndex: 4,
    label: 'Inconsistent Contributor',
    description: 'Demonstrates capacity bursts but lacks role consistency.',
    targetPercentage: 10,
    perf: 'LOW' as const,
    pot: 'MEDIUM' as const,
  },
  {
    boxIndex: 5,
    label: 'Core Player',
    description: 'Solid performance with healthy readiness for next level.',
    targetPercentage: 25,
    perf: 'MEDIUM' as const,
    pot: 'MEDIUM' as const,
  },
  {
    boxIndex: 6,
    label: 'High Performer',
    description: 'Consistently exceeds expectations with strong growth potential.',
    targetPercentage: 15,
    perf: 'HIGH' as const,
    pot: 'MEDIUM' as const,
  },
  {
    boxIndex: 7,
    label: 'Rough Diamond',
    description: 'High leadership capacity requiring tactical skill development.',
    targetPercentage: 5,
    perf: 'LOW' as const,
    pot: 'HIGH' as const,
  },
  {
    boxIndex: 8,
    label: 'High Achiever',
    description: 'Exceeds goals and capable of taking lateral or scale leadership.',
    targetPercentage: 10,
    perf: 'MEDIUM' as const,
    pot: 'HIGH' as const,
  },
  {
    boxIndex: 9,
    label: 'Star / Future Leader',
    description: 'Top-tier performance and highest growth readiness across the org.',
    targetPercentage: 5,
    perf: 'HIGH' as const,
    pot: 'HIGH' as const,
  },
] as const;
